sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.8.0

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" -y docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker build -t dsbaars/go-ethereum go-ethereum/debian-source-develop
  - docker build -t dsbaars/go-ethereum-privatechain go-ethereum/debian-privatechain-develop
